import { readFile, readdir, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const projectRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const publicRoot=path.join(projectRoot,"public");const htmlFiles=[];const problems=[];
async function walk(d){for(const n of await readdir(d)){const f=path.join(d,n),s=await stat(f);if(s.isDirectory())await walk(f);else if(n.endsWith(".html"))htmlFiles.push(f);}}
async function internalPathExists(h){if(h==="/")return true;const r=h.replace(/^\//,"");for(const c of [path.join(publicRoot,r),path.join(publicRoot,r,"index.html"),path.join(publicRoot,`${r}.html`)])try{if((await stat(c)).isFile())return true;}catch{}return false;}
await walk(publicRoot);let jsonLdBlocks=0;
for(const filePath of htmlFiles){const relativeFile=path.relative(publicRoot,filePath),html=await readFile(filePath,"utf8");const req=[["<title>","a title"],["name=\"description\"","a meta description"],["rel=\"canonical\"","a canonical URL"],["<h1","an H1"],["/script.js","the site script"],["/style.css","the shared stylesheet"],["property=\"og:image\" content=\"https://zl3tom.com/social-preview.png\"","an Open Graph preview image"],["name=\"twitter:card\" content=\"summary_large_image\"","a large Twitter/X preview card"],["name=\"twitter:image\" content=\"https://zl3tom.com/social-preview.png\"","a Twitter/X preview image"],["property=\"og:image:width\" content=\"1200\"","the social image width"],["property=\"og:image:height\" content=\"630\"","the social image height"],["property=\"og:image:alt\"","social preview alt text"],["rel=\"me\" href=\"https://www.facebook.com/zl3tom\"","the official Facebook identity link"],[">ZL3TOM on Facebook ↗</a>","the Facebook footer link"]];for(const[n,d]of req)if(!html.includes(n))problems.push(`${relativeFile} is missing ${d}.`);for(const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g))try{JSON.parse(m[1]);jsonLdBlocks++;}catch{problems.push(`${relativeFile} contains invalid JSON-LD.`);}for(const m of html.matchAll(/href="(\/[^"?#]*)/g))if(!(await internalPathExists(m[1])))problems.push(`${relativeFile} contains a broken internal link to ${m[1]}.`);}
const sitemap=await readFile(path.join(publicRoot,"sitemap.xml"),"utf8"),sitemapUrlCount=[...sitemap.matchAll(/<loc>https:\/\/zl3tom\.com[^<]*<\/loc>/g)].length;if(sitemapUrlCount!==29)problems.push(`sitemap.xml has ${sitemapUrlCount} site URLs; expected 29.`);
const guidesIndex=await readFile(path.join(publicRoot,"guides.html"),"utf8"),guideCardCount=(guidesIndex.match(/class="guide-card"/g)||[]).length;if(guideCardCount!==23)problems.push(`The guide index has ${guideCardCount} cards; expected 23.`);
try{const searchIndex=JSON.parse(await readFile(path.join(publicRoot,"search-index.json"),"utf8"));if(searchIndex.length!==sitemapUrlCount)problems.push(`The full-content search index has ${searchIndex.length} pages; expected ${sitemapUrlCount}.`);}catch{problems.push("search-index.json is missing or invalid.");}
const radioPage=await readFile(path.join(publicRoot,"radio-fun.html"),"utf8");if(!radioPage.includes("https://irn.radio/")||!radioPage.includes("https://zmr.godaddysites.com/")||!radioPage.includes("https://networkradios.weebly.com/")||!radioPage.includes("https://anzel.radio/"))problems.push("The Radio Fun page is missing one or more linked radio network links.");if((radioPage.match(/<strong>ZMR Radio<\/strong>/g)||[]).length>0)problems.push("The old standalone ZMR Radio card is still present on Radio Fun.");
const networkGuide=await readFile(path.join(publicRoot,"guides-internet-linked-radio-networks.html"),"utf8");if(!networkGuide.includes("International Radio Network")||!networkGuide.includes("ANZEL Radio")||!networkGuide.includes("ZMR Radio")||!networkGuide.includes("Network Radios"))problems.push("The internet-linked radio networks guide is incomplete.");
for(const [file,needles] of [["guides-first-amateur-radio-contact.html",["Calling CQ on HF","Answering a CQ","Signal reports","Digital voice"]],["guides-network-radios-explained.html",["What is a network radio?","Zello","IRN","ZMR"]],["guides-amateur-radio-from-your-phone.html",["RepeaterPhone","Peanut","EchoLink","QSO One","APRS"]],["guides-peanut-amateur-radio-app.html",["What Peanut is","access code","D-STAR","Fusion","DMR"]],["guides-echolink-getting-started.html",["ZL3TOM-L","304602","ANZEL Radio"]]]){const h=await readFile(path.join(publicRoot,file),"utf8");if(needles.some(n=>!h.includes(n)))problems.push(`${file} is missing requested guide content.`);}
if(problems.length){console.error(problems.join("\n"));process.exitCode=1;}else console.log(`Validated ${htmlFiles.length} HTML files, ${jsonLdBlocks} JSON-LD blocks, ${guideCardCount} guide cards and ${sitemapUrlCount} sitemap URLs.`);
